scene:
    type: Static    
    use_static_obstacles: True
    dual_direction: True
    num_dynamic: 2
    num_box: 1
    reverse_collision: False
    restart_episode: True
    collision_radius: 0.8
    scene_list: ['Perpendicular', 'Towards', 'Parallel', 'Circular']