scene:
  world: l-corridor
  goal_direction: adjacent
  type: Parallel
  use_static_obstacles: False
  dual_direction: False
  num_dynamic: 2
  num_box: 4
  reverse_collision: True
  restart_episode: True
  scene_list: ['Perpendicular', 'Towards', 'Parallel', 'Circular']
  world_list: ['l-corridor', 'corridor', 'open', 'plus-corridor']
  goal_dir_list: ['adjacent', 'straight']
